# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Caesar&nbsp;Wirth'
tagline:          'A Jekyll theme'
description:      'My super cool blog'
url:              http://cjwirth.com
baseurl:          /

excerpt_separator: '<!--excerpt-->'

author:
  name:           'Caesar Wirth'
  url:            https://twitter.com/cjwirth

paginate:         5

facebook:         https://facebook.com/caesar.wirth
twitter:          https://twitter.com/cjwirth
github:           https://github.com/cjwirth
linkedin:         https://www.linkedin.com/in/cjwirth
stackoverflow:    http://stackoverflow.com/users/1403046/cjwirth
