# Permalinks
permalink:        /:categories/:title

# Setup
title:            'Caesar Wirth'
url:              https://cjwirth.com
enforce_ssl:              cjwirth.com

include: ['.well-known']

excerpt_separator: '<!--excerpt-->'

author:
  name:           'Caesar Wirth'
  url:            https://twitter.com/cjwirth

paginate:         5

facebook:         https://facebook.com/caesar.wirth
twitter:          https://twitter.com/cjwirth
github:           https://github.com/cjwirth
linkedin:         https://www.linkedin.com/in/cjwirth
stackoverflow:    http://stackoverflow.com/users/1403046/cjwirth

plugins:
  - jekyll-paginate
